I = imread('dog1.jpg');
BWI = rgb2gray(I);
%BWs = edge(BWI,'canny');
%imshow(E1);
%BWs = edge(BWI, 'sobel');
%imshow(E2);
[~, threshold] = edge(BWI, 'sobel');
fudgeFactor = .5;
BWs = edge(BWI,'sobel', threshold * fudgeFactor);
figure, imshow(BWs), title('binary gradient mask');
se90 = strel('line', 3, 90);
se0 = strel('line', 3, 0);
BWsdil = imdilate(BWs, [se90 se0]);
figure, imshow(BWsdil), title('dilated gradient mask');
BWdfill = imfill(BWsdil, 'holes');
figure, imshow(BWdfill);
title('binary image with filled holes');
BWnobord = imclearborder(BWdfill, 4);
figure, imshow(BWnobord), title('cleared border image');